// Dane flow przygody — Toruń 1454.
// Importowane przez build-review.mjs.

export const GROUPS = {
  G1:  { kolor: 'czerwony',     hex: '#E6194B', frakcja: 'miasto',   opcjonalna: 'Z4'  },
  G2:  { kolor: 'pomaranczowy', hex: '#F58231', frakcja: 'miasto',   opcjonalna: 'Z5'  },
  G3:  { kolor: 'zolty',        hex: '#FFE119', frakcja: 'miasto',   opcjonalna: 'Z5'  },
  G4:  { kolor: 'zielony',      hex: '#3CB44B', frakcja: 'miasto',   opcjonalna: 'Z6'  },
  G5:  { kolor: 'turkusowy',    hex: '#42D4F4', frakcja: 'miasto',   opcjonalna: 'Z6'  },
  G6:  { kolor: 'niebieski',    hex: '#4363D8', frakcja: 'krzyzacy', opcjonalna: 'Z8'  },
  G7:  { kolor: 'fioletowy',    hex: '#911EB4', frakcja: 'krzyzacy', opcjonalna: 'Z8'  },
  G8:  { kolor: 'bialy',        hex: '#FFFFFF', frakcja: 'krzyzacy', opcjonalna: 'Z9'  },
  G9:  { kolor: 'brazowy',      hex: '#9A6324', frakcja: 'krzyzacy', opcjonalna: 'Z10' },
  G10: { kolor: 'czarny',       hex: '#2B2B2B', frakcja: 'krzyzacy', opcjonalna: 'Z10' },
};

export const ETAPY = [
  {
    id: 'E0',
    nr: 0,
    tytul: 'Brief startowy',
    typ: 'wspolny',
    opis: 'Wszyscy uczestnicy zbierają się na Rynku Nowomiejskim. MG rozdaje zapieczętowany list, mapę z symbolami, deszyfrownik (per kolor grupy) i opaskę identyfikacyjną.',
    doSprawdzenia: [
      'Zapieczętowany list: brak czytelnej treści (grafika "sealed" v1-mute)',
      'Ton listu — medievalny, groźba bez anachronizmów',
      'Fizyczna zawartość K1: list + mapa + deszyfrownik + opaska (per kolor)',
    ],
    plikiWspolne: ['wspolne-1-Z1-list.pdf'],
  },
  {
    id: 'E1',
    nr: 1,
    tytul: 'Z1: Szlak symboli',
    typ: 'wspolny-warianty',
    opis: 'Każda z 10 grup dostaje inny łańcuch 4 miejsc (różne deszyfrowniki), ale mechanika identyczna. Raport do MG po 4 krokach.',
    doSprawdzenia: [
      'Koperta Z1: glif startowy (△) = pierwszy glif łańcucha konkretnej grupy (z1-10-sciezek.md)',
      '"exactly four steps" = poprawna długość łańcucha',
      'Mapa: 19 miejsc + 4 landmarki, Piccolo ≡ czytelny, brak nazw (zero spoilerów)',
      'Deszyfrownik: 4 właściwe + 5 dystraktorów, kolor grupy widoczny',
      'Koperta opisuje scenę (kursywa 2. os. "you"), nie list od nadawcy',
    ],
    plikiPerKolor: [
      'wspolne-{kolor}-1-Z1.pdf',
      'wspolne-{kolor}-1-Z1-mapa.pdf',
      'wspolne-{kolor}-1-Z1-deszyfrownik.pdf',
    ],
  },
  {
    id: 'E2',
    nr: 2,
    tytul: 'Z2: Droga do kontaktu',
    typ: 'fork-frakcja',
    opis: 'Pierwsze rozwidlenie per frakcja. TR szuka Jordana (Piccolo), KZ szuka Albrechta. Zagadka logiczna: kto co kupił i gdzie pracuje — tylko jeden glif jest na mapie.',
    doSprawdzenia: [
      'Zagadka logiczna ma jednoznaczne rozwiązanie (Jordan=Piccolo=miecz)',
      'Trzy glify miejsc: jeden realny na mapie (≡ Piccolo), dwa dystraktory',
      'Hasło "kupiłeś dziś rano miecz" — spięte ze skryptem Jordana 1:1',
      'Brak ramki MG (celowe — gracz idzie do Jordana, nie do MG)',
      'Slip "— R." (pośrednik) osobno w kopercie',
    ],
    doSprawdzeniaKZ: [
      'Lustro Z2 TR, ale cel = Albrecht; Pula B plotek (krytyka Zakonu)',
      'Zagadka logiczna: własna trójka (NIE kopia TR)',
      'Trop celu: parol do komtura (nie "chairman Rady")',
      'Pośrednik "N." (nie "R.") — spójność z torem KZ',
      'Jeden glif realny (Albrecht) + dwa dystraktory',
    ],
    plikiPerFrakcja: {
      miasto: ['miasto-{kolor}-2-Z2.pdf', 'miasto-{kolor}-2-Z2-slip.pdf'],
      krzyzacy: ['krzyzacy-{kolor}-2-Z2.pdf'],
    },
  },
  {
    id: 'E3',
    nr: 3,
    tytul: 'Z3/Z3Z: Infiltracja (obowiązkowa)',
    typ: 'fork-frakcja',
    opis: 'Każda frakcja infiltruje siedzibę przeciwnika. TR kradnie listę komturowi Albrechtowi (zamek). KZ obserwuje Jordana w Piccolo i wyciąga godzinę buntu. Kluczowe: obaj aktorzy są tu "celem" przeciwnej frakcji.',
    doSprawdzenia: [
      'TR: instrukcja infiltracji zamku czytelna; brak checkpointu MG po Z3 (raport dopiero po Z3b)',
      'TR: pergamin (łup Z3b) — wpis #1 "chairman" zasiewa finał Z7',
      'TR: klucz do Z7 = motto HELFEN HEILEN UND WEHREN (zaszyfrowane +7 w szyfrgramie)',
      'KZ: cel = obserwacja (kolor szaty + chochla); godzina buntu = 21:00',
      'KZ: Tabela 1 do Z11 — Brown×Ladle = klucz centralny; Albrecht wręcza po Z3Z',
    ],
    plikiPerFrakcja: {
      miasto: [
        'miasto-{kolor}-3-Z3.pdf',
        'miasto-{kolor}-4-Z3b.pdf',
        'miasto-{kolor}-04b-Z3-pergamin.pdf',
      ],
      krzyzacy: ['krzyzacy-{kolor}-3-Z3Z.pdf'],
    },
  },
  {
    id: 'E4',
    nr: 4,
    tytul: 'F2B: Zagadka opcjonalna',
    typ: 'fork-frakcja-grupa',
    opis: 'Każda z 10 grup dostaje INNĄ zagadkę opcjonalną po Z3/Z3Z. TR: Z4 (kalimba, G1), Z5 (piernik, G2+G3), Z6 (herby, G4+G5). KZ: Z8 (kalimba, G6+G7), Z9 (piernik, G8), Z10 (polichromie, G9+G10). Każda wydaje klucz do szyfru finałowego.',
    doSprawdzenia: [
      'Kod 621454 round-trip z zapisem melodii (pręciki numerowane) — Z4/Z8 kalimba',
      '7 słojów + przepis + zmyłkowe nazwy spójne ze stacją i kluczem MG — Z5/Z9 piernik',
      'Karta herbów hanzeatyckich (grafiki u Piotra) — potwierdzić zanim renderować — Z6',
      'Grafiki Biedronki (u Piotra, poza repo) — potwierdzić; Bestiariusz Krzyżowca A/B/E — Z10',
      'Ramka MG obecna w każdej zagadce — gracz wraca do MG z kodem/wynikiem',
    ],
    plikiPerGrupa: {
      G1:  ['miasto-czerwony-5-Z4.pdf',      'miasto-czerwony-5-Z4-audio.mp3'],
      G2:  ['miasto-pomaranczowy-5-Z5.pdf',  'miasto-pomaranczowy-5-Z5-przepis.pdf', 'miasto-pomaranczowy-5-Z5-rozpiska.pdf'],
      G3:  ['miasto-zolty-5-Z5.pdf',         'miasto-zolty-5-Z5-przepis.pdf',        'miasto-zolty-5-Z5-rozpiska.pdf'],
      G4:  ['miasto-zielony-5-Z6.pdf'],
      G5:  ['miasto-turkusowy-5-Z6.pdf'],
      G6:  ['krzyzacy-niebieski-4-Z8.pdf'],
      G7:  ['krzyzacy-fioletowy-4-Z8.pdf'],
      G8:  ['krzyzacy-bialy-4-Z9.pdf',       'krzyzacy-bialy-4-Z9-przepis.pdf',      'krzyzacy-bialy-4-Z9-rozpiska.pdf'],
      G9:  ['krzyzacy-brazowy-4-Z10.pdf'],
      G10: ['krzyzacy-czarny-4-Z10.pdf'],
    },
  },
  {
    id: 'E5',
    nr: 5,
    tytul: 'Z7/Z11: Szyfr finałowy',
    typ: 'fork-frakcja',
    opis: 'TR odszyfrowuje szyfrogram Cezar +7 używając motta z Z3 → odkrywa Jordan = Hans von Baysen. KZ używa Tabeli 1 (kolor×przedmiot→symbol) + tabula recta (klucz MARIENBURG) → dostaje hasło do Albrechta.',
    doSprawdzenia: [
      'Ciphertext = +7 z "HANS VON BAYSEN IS JORDAN THE COOK" (round-trip ręczny)',
      'Dwa nagłówki TYM SAMYM fontem: motto w Z3 (jawne) i w szyfrgramie (zaszyfrowane)',
      'Brak koła/rekwizytu — czysty Cezar; shift odkrywany przez porównanie',
      'Tabula recta: klucz MARIENBURG; round-trip parolu PASS — Z11',
      '"Dziewiąte bicie" = 21:00; NIE "Tuba Dei"; miejsce = Przedzamcze',
    ],
    plikiPerFrakcja: {
      miasto: ['miasto-{kolor}-6-Z7.pdf', 'miasto-{kolor}-06a-Z7-list.pdf'],
      krzyzacy: ['krzyzacy-{kolor}-5-Z11-tabela-symbole.pdf', 'krzyzacy-{kolor}-5-Z11-tabela-recta.pdf'],
    },
  },
  {
    id: 'E6',
    nr: 6,
    tytul: 'Decyzja: komu dostarczyć list',
    typ: 'wspolny',
    opis: 'Każda z 10 grup podejmuje wolny wybór: dostarczyć list Janowi Bażyńskiemu (Jordan) lub komturowi Albrechtowi. TR wie już że Jordan = Bażyński (reveal Z7). KZ zna Albrechta od początku.',
    doSprawdzenia: [
      'Koperta finałowa (KF) — neutralna (nie sugeruje strony)',
      'Wolna decyzja graczy nie jest oceniana w treści koperty',
      'Brak osobnych PDF dla tego etapu — decyzja ustna',
    ],
    plikiWspolne: [],
  },
  {
    id: 'E7',
    nr: 7,
    tytul: 'Finał aktorski: 21:00 pod zamkiem',
    typ: 'wspolny',
    opis: 'Wszystkie 10 grup zbiera się pod ruinami zamku krzyżackiego. MG ogłasza wynik. Scenka aktorska: Bażyński (Piotr) vs Albrecht (Zosia). Callback: Bażyński wyciąga miecz z Z2. Dwie drogi zakończenia (triumf TR / kompromitacja TR).',
    doSprawdzenia: [
      'Scenka: miecz Bażyńskiego = callback parolu z Z2 ("kupiłeś dziś rano miecz")',
      'Aktorzy zajmują strony osobno; grupy wręczają listy bezpośrednio wybranej osobie (Wariant B)',
      'Brak rekwizytu dzwonu (porzucone #49); "dziewiąte bicie" = słowny znacznik czasu',
      'MG-runsheet: skalowanie na 2 tory i 10 grup; protokół awaryjny gdy aktor niedostępny',
    ],
    plikiWspolne: [],
  },

];
